### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by khajavi** [snaketl/vraptor4-angularjs#1]
Is there any maven command to run this project?

**Comment by snaketl** [comment]
Hi @khajavi!

There isn´t a maven command to run. 
You need to package in a war file (mvn package or mvn install) and put the war file on tomcat.
There are two maven projects (two war files), one for backend (api rest) and other for frontend (angular) in this case!

**Comment by khajavi** [comment]
Hi
Thank you Luiz

On Mon, Mar 28, 2016 at 4:30 AM, Luiz Henrique Feltes <
notifications@github.com> wrote:

> Hi @khajavi https://github.com/khajavi!
> 
> There isn´t a maven command to run.
> You need to package in a war file (mvn package or mvn install) and put the
> war file on tomcat.
> There are two maven projects (two war files), one for backend (api rest)
> and other for frontend (angular) in this case!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/snaketl/vraptor4-angularjs/issues/1#issuecomment-202170571

## 

﻿﻿Milād Khājavi
http://blog.khajavi.ir
Having the source means you can do it yourself.
I tried to change the world, but I couldn’t find the source code.
